peers:
  - id: 1
    host: "127.0.0.1"
    port: 3301
  - id: 2
    host: "127.0.0.1"
    port: 3302
  - id: 3
    host: "127.0.0.1"
    port: 3303
  - id: 4
    host: "127.0.0.1"
    port: 3304
sources:
  amqp: # create an amqp source called "inputstream"
    - name: inputstream
      host: localhost:5672
      channel: test
      durable: true
  stdin: true # enable the special "stdin" source

endpoints:
  appendlog: # create an appendlog endpoint called "outfile"
    - name: outfile
      path: ./appendlog.log

triggers:
  - when: stdin
    do: outfile
